export const wordList = [
  { word: "javascript", hint: "A popular programming language for web development" },
  { word: "giraffe", hint: "Tallest living terrestrial animal with a long neck" },
  { word: "pizza", hint: "Italian dish with dough, sauce, and toppings" },
  { word: "volcano", hint: "Mountain that erupts with lava and ash" },
  { word: "oxygen", hint: "Element we breathe to survive" },
  { word: "diamond", hint: "Hardest natural material, often used in jewelry" },
  { word: "kangaroo", hint: "Australian marsupial that carries its young in a pouch" },
  { word: "telescope", hint: "Optical instrument used to observe distant objects" },
  { word: "waterfall", hint: "Natural flow of water descending a steep drop" },
  { word: "bicycle", hint: "Two-wheeled human-powered vehicle" },
  { word: "library", hint: "Place where books and other materials are kept for reading" },
  { word: "rainbow", hint: "Meteorological phenomenon caused by reflection of light in water droplets" },
  { word: "keyboard", hint: "Input device with keys for computers or musical instruments" },
  { word: "dinosaur", hint: "Prehistoric reptile that lived millions of years ago" },
  { word: "parrot", hint: "Colorful tropical bird that can mimic human speech" },
  { word: "mountain", hint: "Large natural elevation of the earth's surface" },
  { word: "camera", hint: "Device used to capture photographs" },
  { word: "elephant", hint: "Largest land animal with a trunk and big ears" },
  { word: "guitar", hint: "Stringed musical instrument with a flat body" },
  { word: "hospital", hint: "Institution providing medical and surgical treatment" },
  { word: "notebook", hint: "Book of blank pages for writing notes" },
  { word: "octopus", hint: "Sea creature with eight arms and a soft body" },
  { word: "sunflower", hint: "Tall plant with large yellow flowers" },
  { word: "vacation", hint: "Period of time devoted to pleasure or relaxation" },
  { word: "whisper", hint: "To speak very softly using one's breath" },
  { word: "xylophone", hint: "Musical instrument with wooden bars struck by mallets" },
  { word: "yacht", hint: "Medium-sized sailboat used for pleasure cruising" },
  { word: "zebra", hint: "African wild horse with black-and-white stripes" },
  { word: "astronaut", hint: "Person trained to travel in a spacecraft" },
  { word: "butterfly", hint: "Insect with large colorful wings that undergoes metamorphosis" },
  { word: "apple", hint: "Fruit that keeps the doctor away" },
  { word: "beach", hint: "Sandy shore by the ocean" },
  { word: "candy", hint: "Sweet treat children love" },
  { word: "daisy", hint: "Simple white-petaled flower" },
  { word: "eagle", hint: "Majestic bird of prey" },
  { word: "fairy", hint: "Mythical tiny magical creature" },
  { word: "grape", hint: "Small round fruit that makes wine" },
  { word: "happy", hint: "Feeling of joy" },
  { word: "igloo", hint: "Dome-shaped ice house" },
  { word: "jelly", hint: "Wobbly fruit-flavored dessert" },
  { word: "koala", hint: "Cute Australian tree hugger" },
  { word: "lemon", hint: "Sour yellow citrus fruit" },
  { word: "mango", hint: "Sweet tropical fruit" },
  { word: "ninja", hint: "Stealthy Japanese warrior" },
  { word: "olive", hint: "Small green Mediterranean fruit" },
  { word: "panda", hint: "Black-and-white bamboo eater" },
  { word: "queen", hint: "Female ruler of a kingdom" },
  { word: "robot", hint: "Programmable machine" },
  { word: "sunny", hint: "Bright weather condition" },
  { word: "tiger", hint: "Striped big cat" },
  { word: "umbra", hint: "Shadow cast during eclipse" },
  { word: "vowel", hint: "A, E, I, O, or U" },
  { word: "water", hint: "H₂O - essential for life" },
  { word: "xenon", hint: "Noble gas used in lights" },
  { word: "yacht", hint: "Fancy recreational boat" },
  { word: "zebra", hint: "Black-and-white striped horse" },
  { word: "acorn", hint: "Oak tree's seed" },
  { word: "badge", hint: "Symbol worn for identification" },
  { word: "cabin", hint: "Wooden house in the woods" },
  { word: "dodge", hint: "Quickly avoid something" }
];